### ISSUE TITLE
allow org_archive in paths?

### ISSUE THREAD

**Issue by shapr** [volhovM/orgstat#6]
I have a six thousand line org file, and a forty three thousand line org_archive for that file, I'd like to do historical trend reports.
Would it be possible to add org_archive as an accepted file extension so I could do historical analysis?

**Comment by volhovm** [comment]
Hello @shapr, thank you for opening the issue!
Not sure it is the optimal way of doing things. It is fairly simple to change the behaviour so that parser considers any passed file as `.org`. But why would you have nonstandard `.org_archive` extension instead of `.org` in the first place?

PS: My archive is just `.org.gpg`.

**Comment by shapr** [comment]
That's the filename that was created when I first archived an item, I thought that was standard.
I'll see if I can customize archive filenames, thanks for the tip.
